//Student Management actions
export const CREATE_STUDENT = 'CREATE_STUDENT';
export const GET_ALL_STUDENTS = 'GET_ALL_STUDENTS';
export const GET_STUDENT = 'GET_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const SET_STUDENT = 'SET_STUDENT';
// Examination management actions
export const CREATE_EXAMINATION = 'CREATE_EXAMINATION';
export const GET_EXAMINAITONS_FOR_TEACHER = 'GET_EXAMINAITONS_FOR_TEACHER';
export const UPDATE_EXAMINATION = 'UPDATE_EXAMINATION';
export const DELETE_EXAMINATION = 'DELETE_EXAMINATION';
export const CREATE_QUESTION = 'CREATE_QUESTION';
export const GET_QUESTIONS_FOR_EXAMINATION = 'GET_QUESTIONS_FOR_EXAMINATION';
export const GET_QUESTIONS_FOR_TEACHER = 'GET_QUESTIONS_FOR_TEACHER';
export const GET_QUESTION = 'GET_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const SET_EXAMINATION = 'SET_EXAMINATION';
export const GET_EXAMINATION_FOR_STUDENT = 'GET_EXAMINATION_FOR_STUDENT';

// Sport Management action types
export const CREATE_SPORT = 'CREATE_SPORT';
export const GET_ALL_SPORT = 'GET_ALL_SPORT';
export const GET_SPORT_FOR_SPORT_INVENTORY = 'GET_SPORT_FOR_SPORT_INVENTORY';
export const SET_SPORT = 'SET_SPORT';
export const GET_SPORT = 'GET_SPORT';
export const GET_COACH_FOR_SPORT = 'GET_COACH_FOR_SPORT';
export const GET_STUDENT_FOR_SPORT = 'GET_STUDENT_FOR_SPORT';
export const UPDATE_SPORT = 'UPDATE_SPORT';
export const DELETE_SPORT = 'DELETE_SPORT';
// User actions
export const USER_LOGIN = 'USER_LOGIN';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';

// Employee actions
export const CREATE_EMPLOYEE_ACCOUNT = 'CREATE_EMPLOYEE_ACCOUNT';
export const GET_ALL_EMPLOYEE_LIST = 'GET_ALL_EMPLOYEE_LIST';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
