// All redux actions goes in here
export const CREATE_EMPLOYEE_ACCOUNT = 'CREATE_EMPLOYEE_ACCOUNT';
export const GET_ALL_EMPLOYEE_LIST = 'GET_ALL_EMPLOYEE_LIST';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';

// Examination management actions
export const CREATE_EXAMINATION = 'CREATE_EXAMINATION';
export const GET_EXAMINAITONS_FOR_TEACHER = 'GET_EXAMINAITONS_FOR_TEACHER';
export const UPDATE_EXAMINATION = 'UPDATE_EXAMINATION';
export const DELETE_EXAMINATION = 'DELETE_EXAMINATION';
export const CREATE_QUESTION = 'CREATE_QUESTION';
export const GET_QUESTIONS_FOR_EXAMINATION = 'GET_QUESTIONS_FOR_EXAMINATION';
export const GET_QUESTIONS_FOR_TEACHER = 'GET_QUESTIONS_FOR_TEACHER';
export const GET_QUESTION = 'GET_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const SET_EXAMINATION = 'SET_EXAMINATION';
